In [259]:
import numpy as numpy
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [260]:
df = pd.read_csv('movies_metadata.csv')

C:\Users\Asu\AppData\Local\Temp\ipykernel_10920\2089594497.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('movies_metadata.csv')

In [261]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [262]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [263]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [264]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [265]:
dataframe = df[[
    'title',
    'genres',
    'overview',
    'tagline',
    'vote_average',
    'vote_count',
    'popularity'
]]

In [266]:
dataframe = dataframe.drop_duplicates().reset_index(drop = True)

In [267]:
dataframe.duplicated().sum()

np.int64(0)

In [268]:
dataframe.head()

,title,genres,overview,tagline,vote_average,vote_count,popularity
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,7.7,5415.0,21.946943
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519

In [269]:
dataframe.isnull().sum()

title               6
genres              0
overview          954
tagline         25045
vote_average        6
vote_count          6
popularity          5
dtype: int64

In [270]:
dataframe = dataframe.dropna(subset=['title'])

In [271]:
dataframe['overview'] = dataframe['overview'].fillna('')
dataframe['tagline'] = dataframe['tagline'].fillna('')

In [272]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [273]:
import ast

def extract_genres(text):
    genres = ast.literal_eval(text)
    return " ".join([genre['name'] for genre in genres])

dataframe['genres'] = dataframe['genres'].apply(extract_genres)

In [274]:
dataframe.head()

,title,genres,overview,tagline,vote_average,vote_count,popularity
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,5415.0,21.946943
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519

In [275]:
dataframe.isnull().sum()

title           0
genres          0
overview        0
tagline         0
vote_average    0
vote_count      0
popularity      0
dtype: int64

In [276]:
dataframe['tags'] = (
    (dataframe['genres'] + ' ') * 4 +
    (dataframe['title'] + ' ') * 2 +
    dataframe['overview'] + ' ' +
    dataframe['tagline']
)

In [277]:
dataframe.head()

,title,genres,overview,tagline,vote_average,vote_count,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,5415.0,21.946943,Animation Comedy Family Animation Comedy Famil...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,Adventure Fantasy Family Adventure Fantasy Fam...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,Romance Comedy Romance Comedy Romance Comedy R...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,34.0,3.859495,Comedy Drama Romance Comedy Drama Romance Come...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,Comedy Comedy Comedy Comedy Father of the Brid...

In [278]:
%pip install nltk

Requirement already satisfied: nltk in e:\D Drive Backup\D Drive Data\Workspace\Udemy ML Course\Python\venv\Lib\site-packages (3.10.0)
Requirement already satisfied: defusedxml in C:\Users\Asu\AppData\Roaming\Python\Python314\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\Asu\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\Asu\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in e:\D Drive Backup\D Drive Data\Workspace\Udemy ML Course\Python\venv\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in C:\Users\Asu\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\Asu\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [279]:
import nltk
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [280]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [281]:
import re

def preprocess(text):
    # Lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Tokenize
    words = text.split()

    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)


dataframe['tags'] = dataframe['tags'].apply(preprocess)

In [282]:
dataframe.head()

,title,genres,overview,tagline,vote_average,vote_count,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,5415.0,21.946943,animation comedy family animation comedy famil...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,adventure fantasy family adventure fantasy fam...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,romance comedy romance comedy romance comedy r...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,34.0,3.859495,comedy drama romance comedy drama romance come...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,comedy comedy comedy comedy father bride part ...

In [283]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [284]:
tfidf = TfidfVectorizer(max_features=50000,stop_words='english', ngram_range=(1,2))

In [285]:
dataframe = dataframe.reset_index(drop=True)

indices = pd.Series(
    data=dataframe.index,
    index=dataframe["title"]
)

# Keep only the first occurrence of duplicate titles
indices = indices[~indices.index.duplicated(keep="first")]

tfidf_matrix = tfidf.fit_transform(dataframe['tags'])

In [286]:
from sklearn.metrics.pairwise import cosine_similarity

%pip install rapidfuzz

Requirement already satisfied: rapidfuzz in e:\D Drive Backup\D Drive Data\Workspace\Udemy ML Course\Python\venv\Lib\site-packages (3.14.5)
Note: you may need to restart the kernel to use updated packages.

In [287]:
from rapidfuzz import process
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

def recommend(title, n=10):
    # Find the closest matching title
    match = process.extractOne(title, indices.index)

    if match is None or match[1] < 60:
        return ["Movie not found"]

    movie_title = match[0]

    idx = indices[movie_title]

    # Handle duplicate titles
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()

    similar_idx = sim_scores.argsort()[::-1][1:n+1]

    return dataframe.iloc[similar_idx]['title'].tolist()

In [288]:
recommend("Toy Story")

['Toy Story 2',
 'Toy Story of Terror!',
 'Botsman i Popugay',
 'The Emoji Movie',
 'Superstar Goofy',
 'Toy Story 3',
 'Despicable Me 2',
 'Banana',
 'Lorenzo',
 'Creature Comforts']

In [289]:
import pickle

# Save TF-IDF matrix
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

# Save title-to-index mapping
pickle.dump(indices, open('indices.pkl', 'wb'))

# Save DataFrame
dataframe.to_pickle('dataframe.pkl')

# Save TF-IDF vectorizer
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

In [291]:
dataframe.columns.tolist()

['title',
 'genres',
 'overview',
 'tagline',
 'vote_average',
 'vote_count',
 'popularity',
 'tags']